name: create_ml_table
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.3.1
  - pip:
      - azure-ai-ml
      - azure-identity
      - numpy
      - pycocotools
      - simplification
      - scikit-image
      - mlflow
